# Generated by Django 5.1.3 on 2024-12-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nest',
            old_name='romm_count',
            new_name='room_count',
        ),
    ]
