# Generated by Django 5.1.3 on 2024-12-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nest', '0002_rename_romm_count_nest_room_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_base',
            field=models.BooleanField(default=False),
        ),
    ]
