# Generated by Django 5.1.3 on 2024-12-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_nestifyuser_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_rooms', models.IntegerField(default=1)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='nestifyuser',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nestifyuser',
            name='name',
            field=models.CharField(default='user-159', max_length=255),
        ),
    ]
