# Generated by Django 5.1.3 on 2024-12-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_nestifyuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nestifyuser',
            name='name',
            field=models.CharField(default='user-745', max_length=255),
        ),
    ]
