# Generated by Django 5.1.3 on 2025-01-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_nestifyuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nestifyuser',
            name='name',
            field=models.CharField(default='user-119', max_length=255),
        ),
    ]
