# Generated by Django 5.1.3 on 2024-12-04 22:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='itempurchase',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='ItemPropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='item.itemproperty')),
            ],
            options={
                'unique_together': {('property', 'value')},
            },
        ),
        migrations.CreateModel(
            name='ItemPropertyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='item.item')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.itemproperty')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.itempropertyvalue')),
            ],
            options={
                'unique_together': {('item', 'property')},
            },
        ),
    ]
