# Generated by Django 5.1.3 on 2025-01-07 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_itemproperty_itempurchase_quantity_itempropertyvalue_and_more'),
        ('nest', '0003_room_is_activated_room_is_base'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='ItemPurchase',
            new_name='ItemPurchased',
        ),
        migrations.RenameModel(
            old_name='RoomItem',
            new_name='RoomItemPurchasedAssignment',
        ),
        migrations.RemoveField(
            model_name='itempropertyvalue',
            name='property',
        ),
        migrations.RemoveField(
            model_name='itempropertyassignment',
            name='property',
        ),
        migrations.AlterUniqueTogether(
            name='itempropertyassignment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='itempropertyassignment',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itempropertyassignment',
            name='value',
        ),
        migrations.AlterUniqueTogether(
            name='itempropertyvalue',
            unique_together=None,
        ),
        migrations.RenameField(
            model_name='roomitempurchasedassignment',
            old_name='item_purchase',
            new_name='item_purchased',
        ),
        migrations.CreateModel(
            name='PropertyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='item.item')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.property')),
            ],
            options={
                'unique_together': {('item', 'property')},
            },
        ),
        migrations.AddField(
            model_name='property',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='item.propertyvalue'),
        ),
        migrations.DeleteModel(
            name='ItemProperty',
        ),
        migrations.DeleteModel(
            name='ItemPropertyAssignment',
        ),
        migrations.DeleteModel(
            name='ItemPropertyValue',
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('name', 'value')},
        ),
    ]
